package com.codewithme.primefitness.global

object SqlTable {
    const val admin =
        "CREATE TABLE ADMIN(ID INTEGER PRIMARY KEY AUTOINCREMENT, USER_NAME TEXT DEFAULT '', PASSWORD TEXT DEFAULT '', MOBILE TEXT DEFAULT '')"
    const val member = "CREATE TABLE MEMBER(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT DEFAULT '', LAST_NAME TEXT DEFAULT '', GENDER TEXT DEFAULT '', AGE TEXT DEFAULT '', WEIGHT TEXT DEFAULT '', MOBILE TEXT DEFAULT '', ADDRESS TEXT DEFAULT '', DATE_OF_JOINING TEXT DEFAULT '', EXPIRE_ON TEXT DEFAULT '', TOTAL TEXT DEFAULT '', IMAGE_PATH TEXT DEFAULT '', STATUS TEXT DEFAULT 'A', IMAGE_PATH_ID_1 TEXT DEFAULT '', IMAGE_PATH_ID_2 TEXT DEFAULT '', DESCRIPTION TEXT DEFAULT '')"
    const val fee = "CREATE TABLE FEE(ID INTEGER PRIMARY KEY AUTOINCREMENT, ONE_MONTH TEXT DEFAULT '', THREE_MONTH TEXT DEFAULT '')"
}